# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XEbXG2rlug74yM41gbI3YezraEV3garq
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

st.write("""
# Division of two numbers
This app takes two number's as input, and divide the First number with Second number and shows result as output
""")

#Get Input

st.header('Input Parameters')

first_number = st.number_input("Enter First Number")
second_number = st.number_input("Enter Second Number")

st.subheader("User Input Parameters")
st.write({ 'first_number': first_number,
           'second_number': second_number })

st.subheader("Result of Division of two numbers is:")
if second_number != 0.0:
  result = (first_number/second_number)
  st.write(result)

